# Generated by Django 4.1.6 on 2023-02-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='picprofile.jpg', upload_to=''),
        ),
    ]
